name-template: "$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Security"
    when:
      label: "security"
  - title: "Breaking changes"
    when:
      label: "breaking"
  - title: "Features"
    when:
      label: "enhancement"
  - title: "Fixes"
    when:
      label: "bug"
  - title: "Dependencies"
    when:
      label: "dependencies"
  - type: "pre-exclude"
    when:
      labels:
        - "tooling"
        - "documentation"
  - type: "version-resolver"
    semver-increment: "major"
    when:
      labels:
        - "major"
        - "breaking"
  - type: "version-resolver"
    semver-increment: "minor"
    when:
      labels:
        - "minor"
        - "enhancement"
  - type: "version-resolver"
    semver-increment: "patch"
    when:
      labels:
        - "patch"
        - "bug"
  - type: "version-resolver"
    semver-increment: "patch"
template: |
  $CHANGES
