name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update-release-draft:
    name: Update Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version-file: ".nvmrc"

      - name: Update Release Draft
        id: release_draft
        uses: release-drafter/release-drafter@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version
        run: npm version ${{ steps.release_draft.outputs.name }} --allow-same-version true --git-tag-version false

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run all

      - name: Commit
        uses: EndBug/add-and-commit@v11
        with:
          push: origin main --force
